language: node_js
node_js:
  - 0.8
env:
    global: 
      - secure: "FAfvrDV0JBMvL7pDTWQZAnhNjNw/8elwWcVFCzPm4jC8XoOZc6gGLLQFedyF\nPZRvf7gBIfc0EUzTOn3nS3FOVkofrEQoHsClNdJAWxIzbQZ0V72VeNBnPKZB\n6x6PMhwFNZzy/Z2ThEC/J6CIHV7wuldsibChZZFpaVNkWQwjvBI="
notifications: 
    email: false