language: node_js
node_js:
  - 0.8
env:
    global: 
        - secure: "IRzwa2mLYIk0YjyoCSMT1JFh+rLiJwkdUB9VZqGs4DUUhFSjCJr4wyIFRTeA\nD8y2tzSjQTa8gkBPsqsMuRSB2Zuc2V+dShA1nS5B3RAjCbBkQnMKsBFxc499\naJW9KXX6Rjqjn3CwqwybYmOaOv4+3CiiXcAMCi0+g9wdJZOIzNo="
notifications: 
    email: false