language: node_js
node_js:
  - 0.8
env:
    global: 
      - secure: "LQYL30G5P+org4uvBfPGcacj802uwLqh2tPHlhjHFh3Rv5tjhS1FiXxVsjoH\nOIv73equy2x/SPUC3agjFmRUgHD7H4HoDvMkQRAiEMH41ByEUMG/0P1rHR7v\nmXTUJ3M6JT3PQTFiq0BuEk33MG+Emcd+y+tpPmF+wZxyubQ7M48="
notifications: 
    email: false