language: node_js
node_js:
  - 0.8
env:
    global: 
      - secure: "Bmk/3B6NnbnIobTbZB8omDPK95ZL48Vadi4nip5c/ybuagJWzyhkPLg2nf1p\nbTu/ilSG4JnhUcqrle6TB0AP7Ua16OpkyMRrwg0+ErtTBLO7D8V1X/ZlrsVT\nm5rOu244TZfLvF1acgFpLuYA8nfioqq0tgkibEeu6fsjgc3VW+A="
notifications: 
    email: false